name: Deploy to Fly.io
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Fly.io CLI
      - name: Install flyctl
        run: curl -L https://fly.io/install.sh | sh

      # Setup app
      - name: Create Fly.io app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          ~/.fly/bin/flyctl auth login --access-token $FLY_API_TOKEN
          ~/.fly/bin/flyctl apps create dc-hungry-bot --json | jq -r .Name > .fly/app-name
          ~/.fly/bin/flyctl volumes create leaderboard_data --size 1 --region lax -a $(cat .fly/app-name)

      # Deploy
      - name: Run deployment
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          ~/.fly/bin/flyctl deploy --remote-only -a $(cat .fly/app-name) \
            --env DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}"
